services:
  db:
    platform: linux/x86_64
    image: mysql:latest
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8090:80"    
    links:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD:  ${MYSQL_ROOT_PASSWORD}
    networks:
      - mysql-phpmyadmin

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    environment:
      - PORT=${PORT_APP}
    ports:
      - '${PORT_APP}:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
    - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:
    driver: bridge

volumes:
  db_data: